name: CI

on:
  push:
    branches:
      - main
      - vercel-hosting
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
        with:
            fetch-depth: 0

      - name: Install Dependencies
        run: npm install

      - name: Linting
        run: npm run lint

      - name: Type Check
        run: npx tsc --noEmit

      - name: Cargo Test
        run: cargo test

      - name: Build
        run: npm run build

      - name: Secret Scanning
        uses: gitleaks/gitleaks-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
  deploy-preview:
    name: deploy-vercel-preview
    needs: build
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    environment: preview
    env:
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
    steps:
      - uses: actions/checkout@v6
      - run: npm install --global vercel@latest

      - name: Pull Vercel environment
        run: vercel pull --yes --environment=preview 

      - name: Build
        run: vercel build 

      - name: Deploy Preview
        run: vercel deploy --prebuilt

  deploy-prod:
    name: deploy-vercel-prod
    needs: build
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest
    environment: production
    env:
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
    steps:
      - uses: actions/checkout@v6
      - run: npm install --global vercel@latest

      - name: Pull Vercel environment
        run: vercel pull --yes --environment=production 

      - name: Build
        run: vercel build --prod

      - name: Deploy
        run: vercel deploy --prebuilt --prod